language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg .; else py.test tests; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
    - python: "3.5"
      env: TEST_PEP8=1
